"""Phase 9G0-R pre-data official-generation binding closure."""

from .contracts import (
    COMMUNICATION_CONFIG_SCHEMA_VERSION,
    LIFECYCLE_CONFIG_SCHEMA_VERSION,
    OFFICIAL_ROLLOUT_CONFIG_SCHEMA_VERSION,
    RECOVERABILITY_EGO_PAYLOAD_SCHEMA_VERSION,
    RECOVERABILITY_ROW_IDENTITY_SCHEMA_VERSION,
    RESIDUAL_RETENTION_K,
)

__all__ = (
    "COMMUNICATION_CONFIG_SCHEMA_VERSION",
    "LIFECYCLE_CONFIG_SCHEMA_VERSION",
    "OFFICIAL_ROLLOUT_CONFIG_SCHEMA_VERSION",
    "RECOVERABILITY_EGO_PAYLOAD_SCHEMA_VERSION",
    "RECOVERABILITY_ROW_IDENTITY_SCHEMA_VERSION",
    "RESIDUAL_RETENTION_K",
)
