"""Binary keep/line pilot: dataset assembly, BCE-only training, validation metrics.

Labels come from the frozen Recovery Event V2 file
(`results/binary_mode_pilot/task_recovery_labels.csv`). Graphs are regenerated by
replaying the same deterministic episodes, so the two are joined by `state_id`.

No class weighting, focal loss, oversampling, outcome balancing, family weighting,
pairwise ranking, split mode, switching, uncertainty head, or threshold tuning.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F

from .config import Config
from .controllers import expert_action
from .dataset import build_graph_arrays
from .environment import SwarmFormationEnv
from .layouts import build_layouts
from .metrics import EpisodeAccumulator
from .splits import TRAIN, VALIDATION, setting_episode_seeds

REPO = Path(__file__).resolve().parent.parent
LABEL_CSV = REPO / "results" / "binary_mode_pilot" / "task_recovery_labels.csv"

MODES = (0, 2)                      # keep, line -- split removed
MODE_NAME = {0: "keep", 2: "line"}
PILOT_FAMILIES = ["line_corridor", "keep_line_keep", "keep_open", "ambiguous"]
TEAM_SIZES = [4, 6]
STATE_STRIDE = 12                    # must match generate_binary_labels.py
EPISODES = {"train": 3, "val": 2}


@dataclass
class PilotSample:
    node_x: torch.Tensor
    edge_index: torch.Tensor
    edge_attr: torch.Tensor
    action_targets: torch.Tensor      # (N, 2 modes, 2)
    recovery_labels: torch.Tensor     # (1, 2)
    state_id: str
    family: str
    team_size: int
    split: str


def load_labels() -> Dict[str, Dict[str, float]]:
    out: Dict[str, Dict[str, float]] = {}
    with LABEL_CSV.open() as fh:
        for r in csv.DictReader(fh):
            out.setdefault(r["state_id"], {})[r["mode"]] = float(r["task_recovery_label"])
    return out


def build_dataset(cfg: Config, split: str, labels: Dict[str, Dict[str, float]]) -> List[PilotSample]:
    """Replay the labelled episodes and attach graphs + expert action targets."""
    split_key = TRAIN if split == "train" else VALIDATION
    samples: List[PilotSample] = []
    for lay in [l for l in build_layouts(split) if l.family in PILOT_FAMILIES]:
        for n in TEAM_SIZES:
            for seed in setting_episode_seeds(split_key, 0, n, EPISODES[split], 0):
                env = SwarmFormationEnv(cfg)
                obs = env.reset(n, "cluttered", seed=seed, layout=lay)
                done, step = False, 0
                while not done:
                    if step % STATE_STRIDE == 0:
                        sid = f"{lay.layout_id}|{n}|{seed}|{step}"
                        lab = labels.get(sid)
                        if lab is not None and {"keep", "line"} <= set(lab):
                            node_x, ei, ea = build_graph_arrays(obs, cfg)
                            acts = np.stack(
                                [expert_action(obs, cfg, m) / cfg.env.max_accel for m in MODES],
                                axis=1).astype(np.float32)
                            samples.append(PilotSample(
                                torch.from_numpy(node_x), torch.from_numpy(ei),
                                torch.from_numpy(ea), torch.from_numpy(acts),
                                torch.tensor([[lab["keep"], lab["line"]]], dtype=torch.float32),
                                sid, lay.family, n, split))
                    obs, _, done, _ = env.step(expert_action(obs, cfg, 0), 0)
                    step += 1
    return samples


def collate(batch: List[PilotSample]) -> Dict[str, torch.Tensor]:
    node_x, edge_attr, edge_index, acts, labels, bidx = [], [], [], [], [], []
    offset = 0
    for b, s in enumerate(batch):
        node_x.append(s.node_x); edge_attr.append(s.edge_attr)
        edge_index.append(s.edge_index + offset)
        acts.append(s.action_targets); labels.append(s.recovery_labels)
        bidx.append(torch.full((s.node_x.shape[0],), b, dtype=torch.long))
        offset += s.node_x.shape[0]
    return {"node_x": torch.cat(node_x), "edge_index": torch.cat(edge_index, dim=1),
            "edge_attr": torch.cat(edge_attr), "action_targets": torch.cat(acts),
            "recovery_labels": torch.cat(labels), "batch_index": torch.cat(bidx)}


# ---------------------------------------------------------------------------
# Loss: BCE only. No ranking term, no weighting of any kind.
# ---------------------------------------------------------------------------
LAMBDA_ACTION = 1.0
LAMBDA_BCE = 1.0


def compute_pilot_loss(out: Dict, batch: Dict, method: str) -> Dict[str, torch.Tensor]:
    zero = batch["node_x"].new_tensor(0.0)
    if method == "topology_agnostic_gnn":
        # No mode conditioning: imitate the KEEP expert only.
        l_action = F.mse_loss(out["actions"], batch["action_targets"][:, 0, :])
        return {"total": LAMBDA_ACTION * l_action, "action": l_action,
                "bce": zero, "ce": zero}

    l_action = F.mse_loss(out["actions_by_topology"], batch["action_targets"])
    if method == "rvt_binary_recovery":
        l_bce = F.binary_cross_entropy_with_logits(
            out["recovery_logits"], batch["recovery_labels"])
        return {"total": LAMBDA_ACTION * l_action + LAMBDA_BCE * l_bce,
                "action": l_action, "bce": l_bce, "ce": zero}
    if method == "direct_keep_line_classifier":
        # Hard best-mode target; ties resolved toward keep (the conservative default).
        lab = batch["recovery_labels"]
        target = (lab[:, 1] > lab[:, 0]).long()
        l_ce = F.cross_entropy(out["class_logits"], target)
        return {"total": LAMBDA_ACTION * l_action + LAMBDA_BCE * l_ce,
                "action": l_action, "bce": zero, "ce": l_ce}
    raise ValueError(method)


# ---------------------------------------------------------------------------
# Validation metrics
# ---------------------------------------------------------------------------
def _auroc(y, s):
    y, s = np.asarray(y), np.asarray(s, float)
    if len(np.unique(y)) < 2:
        return float("nan")
    order = np.argsort(s); ranks = np.empty(len(s), float)
    ranks[order] = np.arange(1, len(s) + 1)
    _, inv, cnt = np.unique(s, return_inverse=True, return_counts=True)
    sums = np.zeros(len(cnt)); np.add.at(sums, inv, ranks); ranks = (sums / cnt)[inv]
    n1, n0 = y.sum(), len(y) - y.sum()
    return float((ranks[y == 1].sum() - n1 * (n1 + 1) / 2) / (n1 * n0))


def _auprc(y, s):
    y, s = np.asarray(y), np.asarray(s, float)
    if y.sum() == 0:
        return float("nan")
    o = np.argsort(-s); y = y[o]
    tp = np.cumsum(y); prec = tp / np.arange(1, len(y) + 1); rec = tp / y.sum()
    return float(np.sum(np.diff(np.concatenate([[0], rec])) * prec))


def _ece(y, p, bins=10):
    y, p = np.asarray(y, float), np.clip(np.asarray(p, float), 0, 1)
    if len(y) == 0:
        return float("nan")
    e = np.quantile(p, np.linspace(0, 1, bins + 1)); e[0], e[-1] = -np.inf, np.inf
    tot = 0.0
    for i in range(bins):
        m = (p > e[i]) & (p <= e[i + 1])
        if m.sum():
            tot += m.mean() * abs(y[m].mean() - p[m].mean())
    return float(tot)


def prediction_metrics(probs: np.ndarray, labels: np.ndarray) -> Dict[str, float]:
    """probs/labels are (S, 2) over {keep, line}."""
    y = labels.reshape(-1)
    p = np.clip(probs.reshape(-1), 1e-7, 1 - 1e-7)
    top1 = float(np.mean(np.argmax(probs, 1) == np.argmax(labels, 1)))
    disagree = labels[:, 0] != labels[:, 1]
    pair = (float(np.mean(np.sign(probs[disagree, 1] - probs[disagree, 0])
                          == np.sign(labels[disagree, 1] - labels[disagree, 0])))
            if disagree.any() else float("nan"))
    pred_line = np.argmax(probs, 1) == 1
    line_req = (labels[:, 1] > labels[:, 0])
    keep_fav = (labels[:, 0] > labels[:, 1])
    return {
        "nll": float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p))),
        "brier": float(np.mean((p - y) ** 2)),
        "auroc": _auroc(y, p), "auprc": _auprc(y, p), "ece": _ece(y, p),
        "top1_mode_accuracy": top1, "pairwise_ranking_accuracy": pair,
        "false_keep_rate": (float(np.mean(~pred_line[line_req])) if line_req.any() else float("nan")),
        "false_line_rate": (float(np.mean(pred_line[keep_fav])) if keep_fav.any() else float("nan")),
        "n_states": int(len(labels)), "n_disagree": int(disagree.sum()),
    }


@torch.no_grad()
def evaluate_supervised(model, samples: List[PilotSample], method: str,
                        batch_size: int = 32) -> Tuple[Dict[str, float], np.ndarray, np.ndarray]:
    model.eval()
    probs, labels, rmses = [], [], []
    for i in range(0, len(samples), batch_size):
        b = collate(samples[i:i + batch_size])
        out = model(b)
        labels.append(b["recovery_labels"].numpy())
        if method == "topology_agnostic_gnn":
            probs.append(np.full((b["recovery_labels"].shape[0], 2), 0.5))
            rmses.append(float(torch.sqrt(F.mse_loss(
                out["actions"], b["action_targets"][:, 0, :]))))
        else:
            probs.append(out["recovery_probs"].numpy())
            rmses.append(float(torch.sqrt(F.mse_loss(
                out["actions_by_topology"], b["action_targets"]))))
    probs, labels = np.concatenate(probs), np.concatenate(labels)
    m = prediction_metrics(probs, labels)
    m["action_rmse_norm"] = float(np.mean(rmses))
    return m, probs, labels


def stratified_metrics(model, samples: List[PilotSample], method: str) -> Dict[str, Dict]:
    """Per N and per family, never pooled only."""
    out: Dict[str, Dict] = {"all": evaluate_supervised(model, samples, method)[0]}
    for n in TEAM_SIZES:
        sub = [s for s in samples if s.team_size == n]
        if sub:
            out[f"N={n}"] = evaluate_supervised(model, sub, method)[0]
    for fam in PILOT_FAMILIES:
        sub = [s for s in samples if s.family == fam]
        if sub:
            out[fam] = evaluate_supervised(model, sub, method)[0]
    return out


# ---------------------------------------------------------------------------
# Closed-loop validation (constrained families only, per the frozen hierarchy)
# ---------------------------------------------------------------------------
def closed_loop_validation(model, cfg: Config, method: str,
                           families=("line_corridor", "keep_line_keep"),
                           episodes: int = 2) -> Dict[str, float]:
    from .policy_runtime import infer_learned_action

    succ, cf, goal = [], [], []
    for lay in [l for l in build_layouts("val") if l.family in families]:
        for n in TEAM_SIZES:
            for seed in setting_episode_seeds(VALIDATION, 0, n, episodes, 0):
                env = SwarmFormationEnv(cfg)
                obs = env.reset(n, "cluttered", seed=seed, layout=lay)
                acc = EpisodeAccumulator(formation_tolerance=cfg.env.formation_tolerance,
                                         dt=cfg.env.dt)
                done, last = False, None
                while not done:
                    rt = infer_learned_action(method, obs, cfg, model, 0)
                    obs, _, done, last = env.step(rt["actions"], rt["topology"])
                    acc.update(last)
                m = acc.finalize(last)
                succ.append(m["success"]); cf.append(m["collision_free"])
                goal.append(m["goal_reached"])
    return {"constrained_success": float(np.mean(succ)),
            "constrained_collision_free": float(np.mean(cf)),
            "constrained_goal_reached": float(np.mean(goal)),
            "episodes": len(succ)}


def selection_key(metrics: Dict[str, float], closed_loop: Dict[str, float]) -> Tuple[float, ...]:
    """Frozen hierarchy: Brier (lower better) -> ranking accuracy -> constrained success."""
    pair = metrics.get("pairwise_ranking_accuracy", float("nan"))
    pair = 0.0 if (pair is None or math.isnan(pair)) else pair
    return (-metrics["brier"], pair, closed_loop["constrained_success"])
