"""Specification-only Phase 8E executable scientific protocol addendum."""

from .protocol import (
    EXECUTABLE_PROTOCOL_SCHEMA_VERSION,
    LAYOUT_EXECUTION_SPECIFICATION_SCHEMA_VERSION,
    SOURCE_POLICY_CONTRACT_SCHEMA_VERSION,
    TARGET_V4_EXECUTION_CONTRACT_SCHEMA_VERSION,
)

__all__ = (
    "EXECUTABLE_PROTOCOL_SCHEMA_VERSION",
    "LAYOUT_EXECUTION_SPECIFICATION_SCHEMA_VERSION",
    "SOURCE_POLICY_CONTRACT_SCHEMA_VERSION",
    "TARGET_V4_EXECUTION_CONTRACT_SCHEMA_VERSION",
)
